#!/usr/bin/env python3
"""Write or verify provenance for the corrected-input Frama-C EVA run."""

import argparse
import hashlib
import json
import os
import platform
import re
import subprocess
from datetime import datetime, timezone
from pathlib import Path


SCHEMA = "weirdmachinebpf.frama-c-eva/v2"
ROOT = Path(__file__).resolve().parents[2]
HERE = Path(__file__).resolve().parent
OUT = HERE / "out"
MANIFEST = OUT / "current.provenance.json"

BOUND_PATHS = {
    "source": HERE / "nand_mod.c",
    "runner": HERE / "run.sh",
    "provenance_tool": Path(__file__).resolve(),
    "eva_log": OUT / "eva_slevel0.current.log",
    "version_record": OUT / "eva_slevel0.current.version.txt",
    "environment": OUT / "environment.current.json",
}

REQUIRED_EXACT_LINES = (
    "a ∈ {0; 1}",
    "b ∈ {0; 1}",
    "0 alarms generated by the analysis.",
)

REQUIRED_SHOW_LINES = (
    re.compile(
        r"\[eva\] .+:[0-9]+: Frama_C_show_each_NAND_out: \{0; 1\}"
    ),
    re.compile(
        r"\[eva\] .+:[0-9]+: Frama_C_show_each_ABLATION_out: \{1\}"
    ),
)


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def load_object(path: Path) -> dict:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"JSON root is not an object: {path}")
    return data


def binding(path: Path) -> dict[str, str]:
    resolved = path.resolve()
    resolved.relative_to(ROOT.resolve())
    if not resolved.is_file() or resolved.stat().st_size == 0:
        raise ValueError(f"missing or empty bound file: {resolved}")
    return {
        "path": resolved.relative_to(ROOT.resolve()).as_posix(),
        "sha256": sha256_file(resolved),
    }


def validate_log_text(text: str) -> None:
    lines = tuple(line.strip() for line in text.splitlines())
    for required in REQUIRED_EXACT_LINES:
        if required not in lines:
            raise ValueError(f"current EVA log lacks exact line: {required}")
    for pattern in REQUIRED_SHOW_LINES:
        if not any(pattern.fullmatch(line) for line in lines):
            raise ValueError(
                f"current EVA log lacks anchored observation: {pattern.pattern}"
            )


def check_log() -> None:
    validate_log_text(BOUND_PATHS["eva_log"].read_text(encoding="utf-8"))


def command_output(command: list[str]) -> str:
    return subprocess.check_output(
        command, text=True, stderr=subprocess.STDOUT
    ).strip()


def write_environment() -> None:
    version = BOUND_PATHS["version_record"].read_text(encoding="utf-8").strip()
    environment = {
        "frama_c_version": version,
        "machine": platform.machine(),
        "python_version": command_output(["python3", "--version"]),
        "uname": command_output(["uname", "-a"]),
    }
    OUT.mkdir(parents=True, exist_ok=True)
    BOUND_PATHS["environment"].write_text(
        json.dumps(environment, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def validate_environment(version: str) -> None:
    environment = load_object(BOUND_PATHS["environment"])
    if environment.get("frama_c_version") != version:
        raise ValueError("environment and Frama-C version record disagree")
    for field in ("machine", "python_version", "uname"):
        value = environment.get(field)
        if not isinstance(value, str) or not value.strip():
            raise ValueError(f"environment lacks non-empty {field}")


def write_manifest() -> None:
    check_log()
    version = BOUND_PATHS["version_record"].read_text(encoding="utf-8").strip()
    write_environment()
    validate_environment(version)
    manifest = {
        "schema": SCHEMA,
        "timestamp_utc": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        "command": ["frama-c", "-eva", "-eva-slevel", "0", "nand_mod.c"],
        "tool_version": version,
        "bindings": {name: binding(path) for name, path in BOUND_PATHS.items()},
        "observations": {
            "nand_global_range": [0, 1],
            "mod7_control_global_range": [1],
            "alarms": 0,
        },
        "scope": "global value ranges only; no input/output relation certificate",
    }
    OUT.mkdir(parents=True, exist_ok=True)
    temporary = MANIFEST.with_suffix(MANIFEST.suffix + ".tmp")
    temporary.write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    os.replace(temporary, MANIFEST)
    print(MANIFEST.relative_to(ROOT))


def verify_manifest() -> None:
    manifest = load_object(MANIFEST)
    if manifest.get("schema") != SCHEMA:
        raise ValueError(f"unexpected Frama-C provenance schema: {manifest.get('schema')!r}")
    if manifest.get("command") != ["frama-c", "-eva", "-eva-slevel", "0", "nand_mod.c"]:
        raise ValueError("Frama-C command binding is missing or unexpected")

    bindings = manifest.get("bindings")
    if not isinstance(bindings, dict) or set(bindings) != set(BOUND_PATHS):
        raise ValueError("Frama-C manifest binding set is incomplete")
    for name, expected_path in BOUND_PATHS.items():
        record = bindings.get(name)
        if not isinstance(record, dict):
            raise ValueError(f"invalid binding for {name}")
        expected_rel = expected_path.resolve().relative_to(ROOT.resolve()).as_posix()
        if record.get("path") != expected_rel:
            raise ValueError(f"path mismatch for {name}")
        if record.get("sha256") != sha256_file(expected_path):
            raise ValueError(f"SHA-256 mismatch for {name}")

    version = BOUND_PATHS["version_record"].read_text(encoding="utf-8").strip()
    if manifest.get("tool_version") != version:
        raise ValueError("Frama-C version record does not match manifest")
    validate_environment(version)
    if manifest.get("observations") != {
        "nand_global_range": [0, 1],
        "mod7_control_global_range": [1],
        "alarms": 0,
    }:
        raise ValueError("Frama-C observation summary is unexpected")
    check_log()
    print("Frama-C provenance audit: ok")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("mode", choices=("write", "verify"))
    args = parser.parse_args()
    if args.mode == "write":
        write_manifest()
    else:
        verify_manifest()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
