#!/usr/bin/env bash
# Capture Frama-C EVA global value ranges for the current two-input model.
# The output filename is distinct so the archived old-model log is not overwritten.
set -euo pipefail

cd "$(dirname "$0")"
mkdir -p out

if ! command -v frama-c >/dev/null 2>&1; then
  echo "frama-c not found. On Ubuntu 24.04: sudo apt-get update && sudo apt-get install -y frama-c-base"
  exit 1
fi

echo "Frama-C: $(frama-c -version 2>/dev/null | head -1)"
echo "Input model: independent a,b via two Frama_C_interval(0,1) calls."
echo "Capturing global value ranges with EVA at slevel 0."
echo "  EXPECT NAND_out     = {0; 1} (exact global range of modulo NAND)"
echo "  EXPECT ABLATION_out = {1}    (different constant mod-7 function)"
echo "These values do not constitute an I/O-relation or completeness result."
python3 -m unittest -v test_current_provenance.py

current_log="out/eva_slevel0.current.log"
frama-c -eva -eva-slevel 0 nand_mod.c > "$current_log" 2>&1
grep -E "Frama_C_show_each" "$current_log"
grep -Eq '^\[eva\] .+:[0-9]+: Frama_C_show_each_NAND_out: \{0; 1\}$' "$current_log"
grep -Eq '^\[eva\] .+:[0-9]+: Frama_C_show_each_ABLATION_out: \{1\}$' "$current_log"
grep -Eq '^[[:space:]]*a ∈ \{0; 1\}$' "$current_log"
grep -Eq '^[[:space:]]*b ∈ \{0; 1\}$' "$current_log"
grep -Eq '^[[:space:]]*0 alarms generated by the analysis\.$' "$current_log"
frama-c -version > out/eva_slevel0.current.version.txt 2>&1
python3 current_provenance.py write
python3 current_provenance.py verify

echo
echo "Current-model log: $current_log"
echo "Version record: out/eva_slevel0.current.version.txt"
echo "Environment: out/environment.current.json"
echo "Provenance: out/current.provenance.json"
echo "Archived old-model log remains unchanged: out/eva_slevel0.log"
echo "Interpretation and limitations: README.md and RESULTS.md"
