#!/usr/bin/env python3
"""Negative tests for fail-closed Frama-C log parsing."""

import unittest

from current_provenance import validate_log_text


VALID = """\
[eva] nand_mod.c:41: Frama_C_show_each_NAND_out: {0; 1}
[eva] nand_mod.c:44: Frama_C_show_each_ABLATION_out: {1}
  a ∈ {0; 1}
  b ∈ {0; 1}
  0 alarms generated by the analysis.
"""


class CurrentProvenanceLogTests(unittest.TestCase):
    def test_accepts_exact_expected_lines(self) -> None:
        validate_log_text(VALID)

    def test_rejects_ten_alarms_as_zero(self) -> None:
        with self.assertRaises(ValueError):
            validate_log_text(
                VALID.replace(
                    "0 alarms generated by the analysis.",
                    "10 alarms generated by the analysis.",
                )
            )

    def test_rejects_data_as_variable_a(self) -> None:
        with self.assertRaises(ValueError):
            validate_log_text(VALID.replace("a ∈ {0; 1}", "data ∈ {0; 1}"))

    def test_rejects_ab_as_variable_b(self) -> None:
        with self.assertRaises(ValueError):
            validate_log_text(VALID.replace("b ∈ {0; 1}", "ab ∈ {0; 1}"))


if __name__ == "__main__":
    unittest.main()
