"""Shared constants for local RAC concretization."""
NOT_INIT = 0
SCALAR_VALUE = 1
PTR_TO_CTX = 2
CONST_PTR_TO_MAP = 3
PTR_TO_STACK = 6

STACK_INVALID = 0
STACK_SPILL = 1
STACK_MISC = 2
STACK_ZERO = 3

SUPPORTED_REG_TYPES = {NOT_INIT, SCALAR_VALUE, PTR_TO_STACK, PTR_TO_CTX, CONST_PTR_TO_MAP}
REG_TYPE_NAMES = {
    NOT_INIT: "NOT_INIT",
    SCALAR_VALUE: "SCALAR_VALUE",
    PTR_TO_CTX: "PTR_TO_CTX",
    CONST_PTR_TO_MAP: "CONST_PTR_TO_MAP",
    PTR_TO_STACK: "PTR_TO_STACK",
}
